[package]
name = "gdvgrab"
version = "0.1.0"
authors = ["oyvindln <oyvindln@users.noreply.github.com>"]

[dependencies]
config_file_handler = "0.9.0" 
serde = "1.0.25"
serde_derive = "1.0.27"

[dependencies.subprocess]
version = "0.1.12"

[dependencies.gtk]
version = "0.3.0"
