[package]
name = "gdvgrab"
version = "0.2.0"
authors = ["oyvindln <oyvindln@users.noreply.github.com>"]

[dependencies]
config_file_handler = "0.11.0" 
serde = "1.0.137"
serde_derive = "1.0.137"

[dependencies.subprocess]
version = "0.2.0"

[dependencies.gtk]
version = "0.8.0"
